### ISSUE TITLE
Missing app: OnionShare (=>2.3)

### ISSUE THREAD

**Issue by AnonyPla** [Perelandra0x309/secure-im#100]
OnionShare 2.3 and higher now provides messaging capabilities and is recommended by the Tor Project.

**Comment by Perelandra0x309** [comment]
Oh now this is something!  Tor is a great network to build apps on, and I've used OnionShare before.  At first I was thinking this was going to be a desktop only solution for chatting.  But I just installed it, and you only need one desktop device to act as the chat server, all participants in the chat actually connect via the Tor Browser.  So you can use this on desktops and mobile devices!  OK I am really liking this.

Thanks for the alert about this.

**Comment by Perelandra0x309** [comment]
Tested and I really like it.  It's not something you can really leave up and running like a regular chat app, it's more for when everyone can be actively online.  This is a great option when you need to ensure a private conversation.  Added a review for OnionShare and added it to my favorites page.

**Comment by AnonyPla** [comment]
As a side-note :) I referenced your guide on my project: https://github.com/AnonymousPlanet/thgtoa (https://anonymousplanet.org) which is under the same licensing than your website. My project also contains kind of a similar table than yours.
