### ISSUE TITLE
Wickr has been acquired by Amazon

### ISSUE THREAD

**Issue by M9fJx5UJarnDjHdfNZoz** [Perelandra0x309/secure-im#103]
https://www.theverge.com/2021/6/25/22550361/amazon-wickr-aws-secure-messaging-encryption

**Comment by Perelandra0x309** [comment]
Yeah Amazon needed to fill in a hole in their services offering to win US Govt contract.  Not quite the same as Facebook buying Whatsapp to get your data, but still being owned by one of the big tech giants is not good.

**Comment by Perelandra0x309** [comment]
Noted in updated review.
