### ISSUE TITLE
Apps not recommended for other reasons: Jitsi

### ISSUE THREAD

**Issue by Perflyst** [Perelandra0x309/secure-im#11]
Why is Jitsi not recommend? There is no reason on your site.
It is open source and has a community.

**Comment by Perelandra0x309** [comment]
If I remember it is because Jitsi is primarily a video conferencing application.  My list focuses on text messaging as the primary usage.  Does Jitsi have a non-video messaging ability?

**Comment by Perflyst** [comment]
Correct, Jitsi is a secure videoconferencing solution. I found nothing about chatting or file sharing.
