### ISSUE TITLE
More to investigate

### ISSUE THREAD

**Issue by Perelandra0x309** [Perelandra0x309/secure-im#25]
Sudo- https://sudoapp.com- iOS only right now
https://bitchat.im- Windows and Ubuntu
Disa- http://disa.im/index.html
OnionShare
Brabbler Ginlo https://www.ginlo.net/en- currently in beta

**Comment by Perelandra0x309** [comment]
OnionShare is more about sharing files, not messaging.
Bitchat is dead.
Made Brabbler it's own issue since the final release is coming soon.
The others have been added

**Comment by mva1985** [comment]
bitchat.im seems to work just fine

your link has a hyphen attached to the end of it that throws things off

**Comment by Perelandra0x309** [comment]
Thanks!  Darn github auto link creation.  I'll create an issue for Bitchat to get to it later.
