### ISSUE TITLE
Conversations (XMPP)

### ISSUE THREAD

**Issue by John3** [Perelandra0x309/secure-im#48]
You have "Requires Phone# or Email" with "Email" with color red, but actually Conversations don't ask you about any email, just an account (xmpp address).... you can create one without hassle. 1) tick "Register new account on server" put any name account and password, then create, that's it.

**Comment by Perelandra0x309** [comment]
Ah, you are right.  I just created a 6 month trial account on conversations.im.  I will update this.  Thanks!
