### ISSUE TITLE
Couple of recommendations

### ISSUE THREAD

**Issue by mva1985** [Perelandra0x309/secure-im#49]
https://zom.im/
https://peerio.com/
https://zyptonite.com/zyptonite/

**Comment by Perelandra0x309** [comment]
https://support.peerio.com/hc/en-us/categories/200275965-How-to-use-Peerio

https://app.zyptonite.com- 
![image](https://user-images.githubusercontent.com/22124003/54475014-84dfd580-47c2-11e9-867c-fa6a794f69fa.png)

**Comment by Perelandra0x309** [comment]
Oops- Peerio is closing down
https://support.peerio.com/hc/en-us/articles/360021688172-Peerio-Service-Closure-FAQs

**Comment by Perelandra0x309** [comment]
I have added all 3 to the website.  I had seen Zom before but forgot about it.  Thanks for the suggestions!
