### ISSUE TITLE
Ricoched maybe dead??

### ISSUE THREAD

**Issue by John3** [Perelandra0x309/secure-im#50]
Not sure how you should put this in the app matrix, maybe removed or add some note....dunno. Is not dead but the development ceased... 😕 

you can read more here and see the last commit date https://github.com/ricochet-im/ricochet/issues/578

**Comment by Perelandra0x309** [comment]
Yes I had linked to Issue #555 back when I did the original review (over a year ago now, wow!) and looks like this one adds more info to the status.  s-rah has moved to focusing on developing Cwtch, which I recently reviewed.  I will make some updates on the Ricochet review with this info.

**Comment by Perelandra0x309** [comment]
Updated the review.  I really appreciate your efforts to keep the info up to date. :thumbsup:
