### ISSUE TITLE
Silent Phone, Kedr, Minds, unsend.it

### ISSUE THREAD

**Issue by Perelandra0x309** [Perelandra0x309/secure-im#60]
Suggestions from C.

**Comment by Perelandra0x309** [comment]
unsend.it website occupied by squatters with sponsored links, last update in app store was 2 years ago.  Looks abandoned.

Kedr- not too bad.  No phone or email required.  Sen text, photos, videos, video chat.  No quoting.  Delete message for just yourself or for all.

**Comment by Perelandra0x309** [comment]
Silent Circle is an enterprise level product with $9.95/mo price.

**Comment by macandchief** [comment]
On the website it says for twinme that it has no trackers but it has google firebase analytics atm. Also, Jami works without google play services. Besides, I really don't get how something like twinme, which is closed source, can be top tier recommendation. It just makes no sense to me.

**Comment by Perelandra0x309** [comment]
TwinMe has the library included because it is declared as a dependency of another library that TwinMe uses, but the analytics code is never actually invoked.  I have had discussions with the president of TwinMe directly and he has answered my questions to my satisfaction.  I have also inspected the code and there are no calls or usage of the firebase analytics classes in any of the twinme code.  So the classes are there but never used.
I have also monitored the network traffic while using TwinMe and it never reaches out to a google server.  I am fully satisfied that there are no active trackers being used.

If you wish to comment further please open a new issue instead of hijacking an unrelated one.  Thanks.

**Comment by macandchief** [comment]
"I have also inspected the code..." - TwinMe is a closed source application. How did you inspect the source code?

**Comment by Perelandra0x309** [comment]
Can't find any info on Minds encryption.
