### ISSUE TITLE
Incorrect information on XMPP

### ISSUE THREAD

**Issue by muppeth** [Perelandra0x309/secure-im#63]
XMPP clients do not require phone numbers nor email addresses to operate. The clients specified in your list for sure don't. I personally don't know of any (apart from quicksy which you list seperatelly) that do.

What does `Leaks files` mean exactly?
`Puddle test` `Hammer test` very much depends on server setup. Most servers I am aware of, allow to enable user to decide not to store any messages on the server. Most of the servers do have retention clearly specified which means even if user decides to store history of the chat on the server, this will be deleted upon the retention period automatically on the server.

`  - SHA-1 hash of your password. Improperly configured servers may store passwords in plaintext.`
Very much depends on the server settings. I doubt service providers use sha-1 at this point not to mention plain text.

**Comment by Perelandra0x309** [comment]
Yes I admit this page needs some work.  The categories there were really meant for use with specific applications.  They do not have much meaning when trying to cover a protocol that is used by so many clients of various quality and specific implementations.  I think I will need to redo that page, it was kind of left over after my last major site redesign as a todo.

Leaks files means that other applications have access to unencrypted data like files or photos (most common) that are sent as a part of a message and the client saves it to disk.  On Android these files are located in the public storage space unencrypted.  On PCs they files may be stored anywhere on the drive.  iOS have very good data isolation between apps so the app would need to deliberately save photos to the Photos app to leak them.

**Comment by Perelandra0x309** [comment]
I redid the protocols page since many of the categories listed are really client specific so were a bit confusing.
