### ISSUE TITLE
On the website...

### ISSUE THREAD

**Issue by Perelandra0x309** [Perelandra0x309/secure-im#67]
On the website it says for twinme that it has no trackers but it has google firebase analytics atm. Also, Jami works without google play services. Besides, I really don't get how something like twinme, which is closed source, can be top tier recommendation. It just makes no sense to me.

_Originally posted by @macandchief in https://github.com/Perelandra0x309/secure-im/issues/60#issuecomment-562811554_

**Comment by Perelandra0x309** [comment]
https://github.com/Perelandra0x309/secure-im/issues/60#issuecomment-562897547

**Comment by macandchief** [comment]
"I have also inspected the code..." - TwinMe is a closed source application. How did you inspect the source code?

**Comment by Perelandra0x309** [comment]
You can download the APK to your computer and use Android Studio to look at the application.  All the classes are there to inspect and you can search for function usage to see which functions are being called.  Non of the Firebase Analytics functions are being called.
