### ISSUE TITLE
Add Get session

### ISSUE THREAD

**Issue by pirboazo** [Perelandra0x309/secure-im#77]
Hi , your study is very interesting .
i would like your comment on https://getsession.org/  im supported by LOKI Crypto blockchain.

Thank a lot .
Pierre

**Comment by KeeJef** [comment]
Just a note, Session is the rebrand of Loki messenger, so i would recommend you simply make changes to the existing Loki messenger review

**Comment by Perelandra0x309** [comment]
Thanks for the note.  Yes I will get to this, maybe this weekend.  It was only released a month or so ago so I was waiting for a little time to give them a chance to get some bugs worked out.
