### ISSUE TITLE
Revisit Riot

### ISSUE THREAD

**Issue by yuuki-san** [Perelandra0x309/secure-im#80]
It's name changed to "Element" and is better than ever (e.g. E2E is ON by default)

**Comment by Perelandra0x309** [comment]
Thanks for the reminder, I have been meaning to do this for a while.  Changed name to Element and updated encryption by default value.
https://github.com/Perelandra0x309/secure-im/commit/462fcdcb6fbd9f941aeb752f572df061efb5af6b
https://github.com/Perelandra0x309/secure-im/commit/bac6be9029fa7261663c251a7864ebde1a21c73e
