### ISSUE TITLE
Some comments on Element

### ISSUE THREAD

**Issue by tulir** [Perelandra0x309/secure-im#81]
Some comments on https://securechatguide.org/decentralizedapps.html#element

> Android app is a web app

[Element Android](https://github.com/vector-im/element-android) is a native Android app written in Kotlin. Riot Android was also a native app (Java).

> Riot uses Olm for one on one chats and Megolm for group chats.

All chats use Megolm (because users in 1:1 chats can have more than one device). Olm is only used for exchanging Megolm keys between individual devices.

> Also no files by default are encrypted.

Files uploaded to encrypted rooms have always been encrypted and private chats are encrypted by default nowadays.

> Server keeps track of every time you login/logout/open client without any retention time indefinatelly since the moment you created an account (that data consists of timestamp, user agent, your ip and your token

> Server keeps indefinatelly every IP address you have used since you created account

Synapse only keeps 28 days of IP logs by default: https://github.com/matrix-org/synapse/blob/v1.25.0/docs/sample_config.yaml#L404-L408. I'm fairly certain the same setting applies to user agents too.

**Comment by Perelandra0x309** [comment]
Just a note for myself, will probably update my Element/Matrix review soon.  Matrix is getting more integrated with other non encrypted chat services.  One of the Matrix goals is indeed to be the central hub for all your communications on all other platforms.  So while rooms in Matrix may be encrypted, your data is probably also being synced with other non-matrix channels and not encrypted.  This makes it very difficult to know whether what you say in a room is totally E2EE everywhere.
This will probably make me change the encryption by default flag to no.

**Comment by Perelandra0x309** [comment]
I removed most of these bullets in the review since they are now mostly moot.  Bridges now makes Element/Matrix no longer encrypted by default or foolproof.  This app is no longer a recommendation.

**Comment by tulir** [comment]
That's more or less completely incorrect. Rooms don't get magically bridged into unencrypted services, someone has to explicitly set it up. In most cases, rooms being bridged are public and therefore intentionally unencrypted on the Matrix side as well.
