### ISSUE TITLE
Sticky header to improve readability

### ISSUE THREAD

**Issue by Werve** [Perelandra0x309/secure-im#84]
Since the table in https://securechatguide.org/featuresmatrix.html is quite long, for a better view you could use css "position: sticky;" in the table row with the columns description.
(an immediate solution would be as described https://css-tricks.com/position-sticky-and-table-headers/)

**Comment by Perelandra0x309** [comment]
Yes this table is not ideal, I spent a lot of time trying to get it working.  It uses a script from http://tablefilter.free.fr to enable all the filtering of columns which I think is more important.  I don't know if customizing the CSS will work with this custom javascript.  Unfortunately I don't think I'd have the time to really work on that now.

**Comment by Perelandra0x309** [comment]
Cleaning up.  Thank for the PR!
