### ISSUE TITLE
Update Signal "Notes" section.

### ISSUE THREAD

**Issue by John3** [Perelandra0x309/secure-im#92]
Not sure if you need more discussion about this or what other people think, I always think that signal is "partially open" or really people think the signal server have 1 year without update? I know there is more moving part and maybe I missing something don't know.

There is some discussion around this, with no conclusion. As you may know one controversial function was added, the PIN with the "cloud contact, settings backup" and the code is not open source. You should update the "Notes" section with that information.

- https://github.com/signalapp/Signal-Server
- https://github.com/signalapp/zkgroup
- https://github.com/signalapp/SecureValueRecovery

**Comment by Perelandra0x309** [comment]
Good points, there aren't any recent releases of the server either.  Is the Github repo just a copy of an older version?
https://github.com/signalapp/Signal-Server/releases

**Comment by Perelandra0x309** [comment]
Added some notes and changed to be partial open.
