### ISSUE TITLE
Update Threema

### ISSUE THREAD

**Issue by John3** [Perelandra0x309/secure-im#94]
It is more open source that before, it is very likely that the client can be build to be release on F-Droid if some libraries are removed. Recently audited https://threema.ch/en/faq/code_audit

- https://threema.ch/en/open-source

- https://threema.ch/en/faq/source_code

- https://github.com/threema-ch

- License https://www.gnu.org/licenses/agpl-3.0.en.html

- https://securechatguide.org/centralizedapps.html#threema

Last time tested: 11/24/2018 Version tested: 3.55

[Last release](https://threema.ch/en/whats-new) Feb 3, 2021 - Version 4.5 - Android 4.6 iOS

**Comment by Perelandra0x309** [comment]
Updated audit and open source links.  I still thinks it's partially open because the server is not open sourced.  Thanks for the info.
