### ISSUE TITLE
Request for removal and/or information update of several apps on the Centralized Apps list

### ISSUE THREAD

**Issue by subsys-R9boq8** [Perelandra0x309/secure-im#98]
Eleet
I searched the web and found that eleet (later changed their name to corpchat)'s domain (both eleet.im and corpchat.com , acquired from the app's play store webpage) has expired, and a visit to corpchat.com landed me in a domain parking page. This lead me to believe in the app's cease of functioning.

KryptoChat : unconfirmed
Visiting the website of KryptoChat landed me in an SSL error bad certificate domain. Visiting the certificate domain directed me to a website of Kryptotel. KryptoChat's webpage seems to be migrated to https://www.kryptotel.net/en/kryptochat/ instead of https://www.kryptochat.com/ 

Ravn
Both the link on the list (ravnapp.com) or the the developer website shown on Google Play store (www.ravnapp.com) does not function properly. Last update date on Google Play store is October 26, 2019. This lead me to believe in the app's cease of functioning.

**Comment by Perelandra0x309** [comment]
Moved these apps to the rejected list.
