### ISSUE TITLE
Request of information update: Session completed its 3rd party code audit.

### ISSUE THREAD

**Issue by subsys-R9boq8** [Perelandra0x309/secure-im#99]
QuarksLab has published the audit report of the decentralized chat application Session.

Session:
https://getsession.org/session-code-audit/
QuarksLab:
https://blog.quarkslab.com/audit-of-session-secure-messaging-application.html
Report:
https://blog.quarkslab.com/resources/2021-05-04_audit-of-session-secure-messaging-application/20-08-Oxen-REP-v1.4.pdf

**Comment by Perelandra0x309** [comment]
Thanks for this, I had heard of the audit but haven't had a chance to follow up to get details.

**Comment by Perelandra0x309** [comment]
Thanks for the info, I have updated the website with this audit.
